version: "3"
services:
  #PHP Service
  face-plus-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: face-plus-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - proxy

  #Nginx Service
  face-plus-server:
    image: nginx:alpine
    container_name: face-plus-server
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.face-plus.entrypoints=http"
      - "traefik.http.routers.face-plus.rule=Host(`face-plus.cekingx.my.id`)"
      - "traefik.http.middlewares.face-plus-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.face-plus.middlewares=face-plus-https-redirect"
      - "traefik.http.routers.face-plus-secure.entrypoints=https"
      - "traefik.http.routers.face-plus-secure.rule=Host(`face-plus.cekingx.my.id`)"
      - "traefik.http.routers.face-plus-secure.tls=true"
      - "traefik.http.routers.face-plus-secure.tls.certresolver=http"
      - "traefik.http.routers.face-plus-secure.service=face-plus"
      - "traefik.http.services.face-plus.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"


#Docker Networks
networks:
  proxy:
    external: true
